#!/bin/bash

set -e

DEBIANVERSION=$(head -1 debian/changelog | cut -d "(" -f 2 | cut -d ")" -f 1 | cut -d "-" -f 1)
echo DEBIANVERSION $DEBIANVERSION
# GITCOMMIT == <git commit id> if DEBIANVERSION like "[0-9]+.[0-9]+.[0-9]+\+git<git commit id>"
# GITCOMMIT == rear-DEBIANVERSION if DEBIANVERSION like "[0-9]+.[0-9]+(.[0-9]+)?
GITCOMMIT=$(echo ${DEBIANVERSION} | cut -d "+" -f 2 | cut -c12-)
if [[ "${GITCOMMIT}X" == "X" ]]; then
  GITCOMMIT=rear-${DEBIANVERSION}
fi
echo GITCOMMIT $GITCOMMIT

git clone -q git://github.com/rear/rear.git debian/rear_repo
cd debian/rear_repo
git checkout -q $GITCOMMIT
OUTNAME=rear_${DEBIANVERSION}
git ls-tree -r --name-only --full-tree $GITCOMMIT | \
tar -czf ../../../${OUTNAME}.orig.tar.gz \
  --transform="s,^,${OUTNAME}/,S" --files-from=-
cd ../..
rm -rf debian/rear_repo
echo "Created tarbal ../${OUTNAME}.orig.tar.gz"
