#!/bin/bash

set -e

DEBIANVERSION=$(head -1 debian/changelog | cut -d "(" -f 2 | cut -d ")" -f 1 | cut -d "-" -f 1)
# GITCOMMIT == <git commit id> if DEBIANVERSION like "[0-9]+.[0-9]+.[0-9]+\+git<git commit id>"
# GITCOMMIT == rear-DEBIANVERSION if DEBIANVERSION like "[0-9]+.[0-9]+(.[0-9]+)?
GITCOMMIT=$(echo ${DEBIANVERSION} | cut -d "+" -f 2 | cut -c12-)
if [[ "${GITCOMMIT}X" == "X" ]]; then
  GITCOMMIT=rear-${DEBIANVERSION}
fi

git clone -q git://github.com/rear/rear.git debian/rear_repo
cd debian/rear_repo
# patch -p 1 <<EOF
#diff -rupN rear_1.14/doc/rear.8 rear-1.14/doc/rear.8
#--- rear_1.14/doc/rear.8	2012-10-03 18:54:11.000000000 +0200
#+++ rear-1.14/doc/rear.8	2012-09-27 16:12:09.000000000 +0200
#@@ -1,13 +1,22 @@
# '\" t
# .\"     Title: rear
# .\"    Author: [see the "AUTHORS" section]
#-.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
#-.\"      Date: 7 Jun 2011
#-.\"    Manual: \ \&
#-.\"    Source: \ \&
#+.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
#+.\"      Date: 09/27/2012
#+.\"    Manual: [FIXME: manual]
#+.\"    Source: [FIXME: source]
# .\"  Language: English
# .\"
#-.TH "REAR" "8" "7 Jun 2011" "\ \&" "\ \&"
#+.TH "REAR" "8" "09/27/2012" "[FIXME: source]" "[FIXME: manual]"
#+.\" -----------------------------------------------------------------
#+.\" * Define some portability stuff
#+.\" -----------------------------------------------------------------
#+.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#+.\" http://bugs.debian.org/507673
#+.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
#+.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#+.ie \n(.g .ds Aq \(aq
#+.el       .ds Aq '
# .\" -----------------------------------------------------------------
# .\" * set default formatting
# .\" -----------------------------------------------------------------
#
#EOF
git checkout -q $GITCOMMIT
OUTNAME=rear_${DEBIANVERSION}
git ls-tree -r --name-only --full-tree master | \
tar -czf ../../../${OUTNAME}.orig.tar.gz \
  --transform="s,^,${OUTNAME}/,S" --files-from=-
cd ../..
rm -rf debian/rear_repo
echo "Created tarbal ../${OUTNAME}.orig.tar.gz"
