Document: rear
Title: Debian rear Manual
Author: <insert document author here>
Abstract: This manual describes what rear is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rear/rear.sgml.gz

Format: postscript
Files: /usr/share/doc/rear/rear.ps.gz

Format: text
Files: /usr/share/doc/rear/rear.text.gz

Format: HTML
Index: /usr/share/doc/rear/html/index.html
Files: /usr/share/doc/rear/html/*.html
